let
  # Common fonts shared across Word, Excel, and PowerPoint
  wepCommon = [
    "AbadiMTCondensedExtraBold.ttf"
    "AbadiMTCondensedLight.ttf"
    "angsa.ttf"
    "angsab.ttf"
    "angsai.ttf"
    "angsaz.ttf"
    "Aptos-Black-Italic.ttf"
    "Aptos-Black.ttf"
    "Aptos-Bold-Italic.ttf"
    "Aptos-Bold.ttf"
    "Aptos-ExtraBold-Italic.ttf"
    "Aptos-ExtraBold.ttf"
    "Aptos-Italic.ttf"
    "Aptos-Light-Italic.ttf"
    "Aptos-Light.ttf"
    "Aptos-Narrow-Bold-Italic.ttf"
    "Aptos-Narrow-Bold.ttf"
    "Aptos-Narrow-Italic.ttf"
    "Aptos-Narrow.ttf"
    "Aptos-SemiBold-Italic.ttf"
    "Aptos-SemiBold.ttf"
    "Aptos.ttf"
    "arial.ttf"
    "arialbd.ttf"
    "arialbi.ttf"
    "ariali.ttf"
    "ArialNarrowBoldItalic.ttf"
    "ArialNarrowItalic.ttf"
    "ArialRoundedMTBold.ttf"
    "ariblk.ttf"
    "BaskervilleOldFace.ttf"
    "batang.ttc"
    "Bauhaus93.ttf"
    "BellMT.ttf"
    "BellMTBold.ttf"
    "BellMTItalic.ttf"
    "BernardMTCondensed.ttf"
    "Book Antiqua Bold Italic.ttf"
    "Book Antiqua Bold.ttf"
    "Book Antiqua Italic.ttf"
    "Book Antiqua.ttf"
    "Bookman Old Style Bold Italic.ttf"
    "Bookman Old Style Bold.ttf"
    "Bookman Old Style Italic.ttf"
    "Bookman Old Style.ttf"
    "Bookshelf Symbol 7.ttf"
    "Braggadocio.ttf"
    "BritannicBold.ttf"
    "Calibri.ttf"
    "Calibrib.ttf"
    "Calibrii.ttf"
    "calibril.ttf"
    "calibrili.ttf"
    "Calibriz.ttf"
    "Calisto MT Bold.ttf"
    "Calisto MT Italic.ttf"
    "Calisto MT.ttf"
    "CalistoMTBoldItalic.ttf"
    "Cambria.ttc"
    "Cambriab.ttf"
    "Cambriai.ttf"
    "Cambriaz.ttf"
    "Candara.ttf"
    "Candarab.ttf"
    "Candarai.ttf"
    "Candaraz.ttf"
    "Century Gothic Bold Italic.ttf"
    "Century Gothic Bold.ttf"
    "Century Gothic Italic.ttf"
    "Century Gothic.ttf"
    "Century Schoolbook Bold Italic.ttf"
    "Century Schoolbook Bold.ttf"
    "Century Schoolbook Italic.ttf"
    "Century Schoolbook.ttf"
    "Century.ttf"
    "ColonnaMT.ttf"
    "ComicSansMSBold.ttf"
    "Consola.ttf"
    "Consolab.ttf"
    "Consolai.ttf"
    "Consolaz.ttf"
    "Constan.ttf"
    "Constanb.ttf"
    "Constani.ttf"
    "Constanz.ttf"
    "COOPBL.TTF"
    "CopperplateGothicBold.ttf"
    "Corbel.ttf"
    "Corbelb.ttf"
    "Corbeli.ttf"
    "Corbelz.ttf"
    "cordia.ttc"
    "CurlzMT.ttf"
    "david.ttf"
    "davidbd.ttf"
    "Deng.ttf"
    "Dengb.ttf"
    "Dengl.ttf"
    "Desdemona.ttf"
    "Dubai-Bold.ttf"
    "Dubai-Light.ttf"
    "Dubai-Medium.ttf"
    "Dubai-Regular.ttf"
    "EdwardianScriptITC.ttf"
    "EngraversMT.ttf"
    "EngraversMTBold.ttf"
    "Eurostile Bold.ttf"
    "Eurostile.ttf"
    "Fangsong.ttf"
    "FootlightMTLight.ttf"
    "Franklin Gothic Book Italic.ttf"
    "Franklin Gothic Book.ttf"
    "Franklin Gothic Demi Cond.ttf"
    "Franklin Gothic Demi Italic.ttf"
    "Franklin Gothic Demi.ttf"
    "Franklin Gothic Heavy Italic.ttf"
    "Franklin Gothic Heavy.ttf"
    "Franklin Gothic Medium Cond.ttf"
    "Franklin Gothic Medium Italic.ttf"
    "Franklin Gothic Medium.ttf"
    "Gabriola.ttf"
    "GARA.ttf"
    "GARABD.ttf"
    "GARABDIT.ttf"
    "GARAIT.ttf"
    "Gautami.TTF"
    "Gautamib.ttf"
    "Gill Sans MT Bold Italic.ttf"
    "Gill Sans MT Bold.ttf"
    "Gill Sans MT Condensed.ttf"
    "Gill Sans MT Ext Condensed Bold.ttf"
    "Gill Sans MT Italic.ttf"
    "Gill Sans MT.ttf"
    "GillSansUltraBold.ttf"
    "GloucesterMTExtraCondensed.ttf"
    "Goudy Old Style Bold.ttf"
    "Goudy Old Style Italic.ttf"
    "Goudy Old Style.ttf"
    "gulim.ttc"
    "Haettenschweiler.ttf"
    "Harrington.ttf"
    "HGRGE.ttc"
    "HGRME.ttc"
    "HGRSGU.ttc"
    "HGRSMP.ttf"
    "himalaya.ttf"
    "ImprintMTShadow.ttf"
    "Kaiti.ttf"
    "Kartika.TTF"
    "Kartikab.TTF"
    "KinoMT.ttf"
    "latha.ttf"
    "Lathab.ttf"
    "Lucida Console.ttf"
    "Lucida Sans Demibold Italic.ttf"
    "Lucida Sans Demibold Roman.ttf"
    "Lucida Sans Italic.ttf"
    "Lucida Sans Unicode.ttf"
    "Lucida Sans.ttf"
    "LucidaBlackletter.ttf"
    "LucidaBright.ttf"
    "LucidaBrightDemibold.ttf"
    "LucidaBrightDemiboldItalic.ttf"
    "LucidaBrightItalic.ttf"
    "LucidaCalligraphyItalic.ttf"
    "LucidaFaxDemibold.ttf"
    "LucidaFaxDemiboldItalic.ttf"
    "LucidaFaxItalic.ttf"
    "LucidaFaxRegular.ttf"
    "LucidaHandwritingItalic.ttf"
    "LucidaSansTypewriterBold.ttf"
    "LucidaSansTypewriterBoldOblique.ttf"
    "LucidaSansTypewriterOblique.ttf"
    "LucidaSansTypewriterRegular.ttf"
    "malgun.ttf"
    "malgunbd.ttf"
    "malgunsl.ttf"
    "mangal.ttf"
    "MangalB.ttf"
    "Marlett.ttf"
    "MaturaMTScriptCapitals.ttf"
    "meiryo.ttc"
    "meiryob.ttc"
    "mingliu.ttc"
    "mingliub.ttc"
    "Mistral.ttf"
    "mmrtext.ttf"
    "mmrtextb.ttf"
    "ModernNo.20.ttf"
    "monbaiti.ttf"
    "MonotypeCorsiva.ttf"
    "MonotypeSorts.ttf"
    "MS Reference Sans Serif.ttf"
    "MS Reference Specialty.ttf"
    "msgothic.ttc"
    "MSJH.ttf"
    "MSJHBD.ttf"
    "msmincho.ttc"
    "msyh.ttc"
    "msyhbd.ttc"
    "msyhl.ttc"
    "msyi.ttf"
    "MTEXTRA.ttf"
    "News Gothic MT Bold Italic.ttf"
    "News Gothic MT Bold.ttf"
    "News Gothic MT Italic.ttf"
    "News Gothic MT.ttf"
    "ntailu.ttf"
    "ntailub.ttf"
    "nyala.ttf"
    "Onyx.ttf"
    "pala.ttf"
    "palab.ttf"
    "palabi.ttf"
    "palai.ttf"
    "Perpetua Bold Italic.ttf"
    "Perpetua Bold.ttf"
    "Perpetua Italic.ttf"
    "Perpetua Titling MT Bold.ttf"
    "Perpetua Titling MT.ttf"
    "Perpetua.ttf"
    "Rockwell Bold Italic.ttf"
    "Rockwell Bold.ttf"
    "Rockwell Condensed Bold.ttf"
    "Rockwell Condensed.ttf"
    "Rockwell Extra Bold.ttf"
    "Rockwell Italic.ttf"
    "Rockwell.ttf"
    "Segoe Print Bold.ttf"
    "Segoe Script Bold.ttf"
    "seguihis.ttf"
    "seguisym.ttf"
    "SimHei.ttf"
    "Simsun.ttc"
    "simsunb.ttf"
    "Stencil.ttf"
    "STHUPO.ttf"
    "STLITI.ttf"
    "STXINGKA.ttf"
    "STXINWEI.ttf"
    "STZHONGS.ttf"
    "symbol.ttf"
    "tahoma.ttf"
    "tahomabd.ttf"
    "taile.ttf"
    "TaiLeb.ttf"
    "thsarabun-bold-italic.ttf"
    "thsarabun-bold.ttf"
    "thsarabun-italic.ttf"
    "thsarabun.ttf"
    "times.ttf"
    "timesbd.ttf"
    "timesbi.ttf"
    "timesi.ttf"
    "TrebuchetMSBoldItalic.ttf"
    "Tunga.TTF"
    "Tungab.TTF"
    "Tw Cen MT Bold Italic.ttf"
    "Tw Cen MT Bold.ttf"
    "Tw Cen MT Condensed Bold.ttf"
    "Tw Cen MT Condensed Extra Bold.ttf"
    "Tw Cen MT Condensed.ttf"
    "Tw Cen MT Italic.ttf"
    "Tw Cen MT.ttf"
    "Verdana Bold Italic.ttf"
    "Verdana Bold.ttf"
    "Verdana Italic.ttf"
    "Verdana.ttf"
    "webdings.ttf"
    "WideLatin.ttf"
    "Wingdings 2.ttf"
    "Wingdings 3.ttf"
    "Wingdings.ttf"
    "YuGothB.ttc"
    "YuGothL.ttc"
    "YuGothM.ttc"
    "YuGothR.ttc"
    "yumin.ttf"
    "yumindb.ttf"
    "yuminl.ttf"
  ];

  # Common fonts shared across Only Outlook and Onenote
  ooCommon = [
    "Aptos-Black-Italic.ttf"
    "Aptos-Black.ttf"
    "Aptos-Bold-Italic.ttf"
    "Aptos-Bold.ttf"
    "Aptos-ExtraBold-Italic.ttf"
    "Aptos-ExtraBold.ttf"
    "Aptos-Italic.ttf"
    "Aptos-Light-Italic.ttf"
    "Aptos-Light.ttf"
    "Aptos-Narrow-Bold-Italic.ttf"
    "Aptos-Narrow-Bold.ttf"
    "Aptos-Narrow-Italic.ttf"
    "Aptos-Narrow.ttf"
    "Aptos-SemiBold-Italic.ttf"
    "Aptos-SemiBold.ttf"
    "Aptos.ttf"
    "arial.ttf"
    "arialbd.ttf"
    "arialbi.ttf"
    "ariali.ttf"
    "ariblk.ttf"
    "Calibri.ttf"
    "Calibrib.ttf"
    "Calibrii.ttf"
    "calibril.ttf"
    "calibrili.ttf"
    "Calibriz.ttf"
    "Cambria.ttc"
    "Cambriab.ttf"
    "Cambriai.ttf"
    "Cambriaz.ttf"
    "Consola.ttf"
    "Consolab.ttf"
    "Consolai.ttf"
    "Consolaz.ttf"
    "Constan.ttf"
    "Constanb.ttf"
    "Constani.ttf"
    "Constanz.ttf"
    "Corbel.ttf"
    "Corbelb.ttf"
    "Corbeli.ttf"
    "Corbelz.ttf"
    "Dubai-Bold.ttf"
    "Dubai-Light.ttf"
    "Dubai-Medium.ttf"
    "Dubai-Regular.ttf"
    "GARA.ttf"
    "GARABD.ttf"
    "GARABDIT.ttf"
    "GARAIT.ttf"
    "Gautami.TTF"
    "Gautamib.ttf"
    "himalaya.ttf"
    "Kartika.TTF"
    "Kartikab.TTF"
    "latha.ttf"
    "Lathab.ttf"
    "malgun.ttf"
    "mangal.ttf"
    "MangalB.ttf"
    "meiryo.ttc"
    "meiryob.ttc"
    "mingliu.ttc"
    "mingliub.ttc"
    "monbaiti.ttf"
    "msgothic.ttc"
    "msmincho.ttc"
    "msyi.ttf"
    "seguihis.ttf"
    "seguisym.ttf"
    "SimHei.ttf"
    "Simsun.ttc"
    "symbol.ttf"
    "tahoma.ttf"
    "tahomabd.ttf"
    "thsarabun-bold-italic.ttf"
    "thsarabun-bold.ttf"
    "thsarabun-italic.ttf"
    "thsarabun.ttf"
    "times.ttf"
    "timesbd.ttf"
    "timesbi.ttf"
    "timesi.ttf"
    "Tunga.TTF"
    "Tungab.TTF"
    "webdings.ttf"
    "Wingdings 2.ttf"
    "Wingdings 3.ttf"
    "Wingdings.ttf"
    "YuGothB.ttc"
    "YuGothR.ttc"
  ];
in
{
  word = wepCommon;
  excel = wepCommon;
  powerpoint = wepCommon;
  outlook = ooCommon ++ [
    "Century Gothic Bold Italic.ttf"
    "Century Gothic Bold.ttf"
    "Century Gothic Italic.ttf"
    "Century Gothic.ttf"
    "Century Schoolbook Bold Italic.ttf"
    "Century Schoolbook Bold.ttf"
    "Century Schoolbook Italic.ttf"
    "Century Schoolbook.ttf"
    "Century.ttf"
    "cordia.ttc"
    "david.ttf"
    "davidbd.ttf"
    "Deng.ttf"
    "Dengb.ttf"
    "Dengl.ttf"
    "mmrtext.ttf"
    "mmrtextb.ttf"
    "ntailu.ttf"
    "nyala.ttf"
    "YuGothL.ttc"
    "YuGothM.ttc"
    "yumin.ttf"
  ];
  onenote = ooCommon ++ [
    "batang.ttc"
    "Candara.ttf"
    "Candarab.ttf"
    "Candarai.ttf"
    "Candaraz.ttf"
    "Fangsong.ttf"
    "Gabriola.ttf"
    "gulim.ttc"
    "Kaiti.ttf"
    "Leelauib.ttf"
    "Leelawui.ttf"
    "leeluisl.ttf"
    "malgunbd.ttf"
    "MSJH.ttf"
    "MSJHBD.ttf"
    "msyh.ttc"
    "msyhbd.ttc"
    "msyhl.ttc"
    "MTEXTRA.ttf"
    "Nirmala.ttf"
    "Nirmalab.ttf"
    "Nirmalas.ttf"
    "ONAppleIcon.ttf"
  ];
}
